---
k8s_url_apt_key: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
k8s_gpgpath: /usr/share/keyrings/kubernetes-apt-keyring.gpg
k8s_repository: "https://pkgs.k8s.io/core:/stable:/v1.28/deb/"

marked_packages: 
  - kubeadm
  - kubectl
  - kubelet

packages:
  - kubeadm
  - kubectl
  - kubelet
  - apt-transport-https 
  - ca-certificates 
  - curl

conflicting_packages:
  - docker.io

ufw_rules:
  - proto: tcp 
    port: 10250
    name: "Kubernetes: Kubelet API"   
  - proto: tcp
    port: 7946
    name: "Metallb memberlist traffic"
  - proto: udp
    port: 7946
    name: "Metallb memberlist traffic"
## TODO: This needs updating.. 
# worker only
# sudo ufw allow 30000-32767/tcp NodePort Services
# sudo ufw allow 10250/tcp
# sudo ufw reload
