apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kavita
  name: kavita
  namespace: kavita
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      volumes:
      - name: nfs-kavita-config
        persistentVolumeClaim:
          claimName: kavita-pvc-config
      - name: nfs-kavita-data
        persistentVolumeClaim:
          claimName: kavita-pvc-data
      containers:
      - env:
        - name: TZ
          value: America/New_York       
        image: lscr.io/linuxserver/kavita:latest
        imagePullPolicy: Always
        name: kavita
        ports:
        - containerPort: 5000
          name: http-tcp
        resources:
          limits:
            cpu: "1000m"
            memory: "128Mi"
          requests:
            cpu: "256m"
            memory: "128Mi" 
        volumeMounts:
        - mountPath: /config
          name: nfs-kavita-config
        - mountPath: /data
          name: nfs-kavita-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
