apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-pv-nfs-config   
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi               
  accessModes:
    - ReadWriteMany             
  persistentVolumeReclaimPolicy: Retain  
  nfs:
    path: /volume1/kubedata/kavita/config     
    server: nas.bou1der.net 
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-pv-nfs-data
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi                   # < max. size we reserve for the pv. A bigger value than the configdata
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/kubedata/kavita/data     
    server: nas.bou1der.net
    readOnly: false
