---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
spec:
  destination:
    namespace: fluent-bit 
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.50.0
    chart: fluent-bit
    helm:
      values: |
       config:
        outputs: |
          [OUTPUT]
              Name loki
              Match *
              Host loki.loki.svc.cluster.local
              Port 3100
              Labels job=fluentbit
              Auto_Kubernetes_Labels on              
              tenant_id: test          
  - repoURL: 'https://github.com/bobmaertz/home-ops.git'
    targetRevision: HEAD
    path: kubernetes/orion/manifests/monitoring/fluentbit/
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
