---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin
  namespace: gitea
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: gitea-admin
  data:
    - secretKey: username
      remoteRef:
        key: "gitea_admin"
        property: username
    - secretKey: password
      remoteRef:
        key: "gitea_admin"
        property: password
    - secretKey: email
      remoteRef:
        key: "gitea_admin"
        property: email
