---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-htpasswd
  namespace: registry
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: registry-htpasswd
  data:
    - secretKey: htpasswd
      remoteRef:
        key: "registry_htpasswd"
        property: credential
