apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-nfs-config   
  namespace: jellyfin           
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi               
  accessModes:
    - ReadWriteMany             
  persistentVolumeReclaimPolicy: Retain  
  nfs:
    path: /volume1/kubedata/jellyfin/config     
    server: nas.bou1der.net 
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-nfs-data
  namespace: jellyfin
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti                   # < max. size we reserve for the pv. A bigger value than the configdata
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/kubedata/jellyfin/data     
    server: nas.bou1der.net
    readOnly: false