apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-config  
  namespace: jellyfin        
spec:
  storageClassName: ""
  volumeName: jellyfin-pv-nfs-config  
  accessModes:
    - ReadWriteMany             
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi              
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-data
  namespace: jellyfin
spec:
  storageClassName: ""
  volumeName: jellyfin-pv-nfs-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1T