apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: internal
spec:
  selector:
    app: nginx  # This should match the labels on your NGINX pods
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http