---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: argo-cd
      repoURL:  https://argoproj.github.io/argo-helm
      targetRevision: 7.8.23
      helm:
        values: |
          configs:
            params:
              server.insecure: "true"
          notifications:
            enabled: true
            notifiers:
              service.webhook.discord: |
                url: $discord-webhook-url
                headers:
                - name: Content-Type
                  value: application/json
            triggers:
              trigger.on-app-health-degraded: |
                - when: app.status.health.status == 'Degraded'
                  send: [app-health-degraded]
            subscriptions:
            - recipients:
              - discord
              triggers:
                - on-app-health-degraded
            templates:
              template.app-health-degraded: |
                webhook:
                  discord:
                    method: POST
                    body: |
                      {
                        "embeds": [
                          {
                            "title": "Application {{.app.metadata.name}} has degraded",
                            "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                            "fields": [
                              {
                                "name": "Health Status",
                                "value": "{{.app.status.health.status}}",
                                "inline": "true"
                              },
                              {
                                "name": "Repository",
                                "value": "{{.app.spec.source.repoURL}}",
                                "inline": "false"
                              }
                              {{range $index, $c := .app.status.conditions}}
                              {{if $index}},{{end}}
                              {
                                "name": "{{$c.type}}",
                                "value": "{{$c.message}}",
                                "inline": "true"
                              }
                              {{end}}
                            ]
                          }
                        ]
                      }
    - repoURL: 'https://github.com/bobmaertz/home-ops.git'
      targetRevision: HEAD
      path: kubernetes/orion/manifests/infra/argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
