---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: argo-cd
      repoURL:  https://argoproj.github.io/argo-helm
      targetRevision: 7.8.23
      helm:
        values: |
          configs:
            params:
              server.insecure: "true"
            cm:
              accounts.bob: login
              admin.enabled: "false"
            rbac:
              policy.default: role:admin
          notifications:
            enabled: true
            context:
              argocdUrl: $argocd-url
            notifiers:
              service.webhook.discord: |
                url: $discord-webhook-url
                headers:
                - name: Content-Type
                  value: application/json
            triggers:
              trigger.on-app-health-degraded: |
                - when: app.status.health.status == 'Degraded'
                  send: [app-health-degraded]
              trigger.on-app-sync-failed: |
                - when: app.status.operationState.phase in ['Error', 'Failed']
                  send: [app-sync-failed]
              trigger.on-app-synced: |
                - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
                  send: [app-synced]
            subscriptions:
            - recipients:
              - discord
              triggers:
                - on-app-health-degraded
                - on-app-sync-failed
                - on-app-synced
            templates:
              template.app-sync-failed: |
                webhook:
                  discord:
                    method: POST
                    body: |
                      {
                        "embeds": [
                          {
                            "title": "Sync failed: {{.app.metadata.name}}",
                            "color": 15158332,
                            "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                            "fields": [
                              {
                                "name": "Phase",
                                "value": "{{.app.status.operationState.phase}}",
                                "inline": true
                              },
                              {
                                "name": "Message",
                                "value": "{{.app.status.operationState.message}}",
                                "inline": false
                              }
                            ]
                          }
                        ]
                      }
              template.app-synced: |
                webhook:
                  discord:
                    method: POST
                    body: |
                      {
                        "embeds": [
                          {
                            "title": "Deployed: {{.app.metadata.name}}",
                            "color": 3066993,
                            "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                            "fields": [
                              {
                                "name": "Sync Status",
                                "value": "{{.app.status.sync.status}}",
                                "inline": true
                              },
                              {
                                "name": "Revision",
                                "value": "{{.app.status.sync.revision}}",
                                "inline": true
                              }
                            ]
                          }
                        ]
                      }
              template.app-health-degraded: |
                webhook:
                  discord:
                    method: POST
                    body: |
                      {
                        "embeds": [
                          {
                            "title": "Application {{.app.metadata.name}} has degraded",
                            "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                            "fields": [
                              {
                                "name": "Health Status",
                                "value": "{{.app.status.health.status}}",
                                "inline": true
                              },
                              {
                                "name": "Repository",
                                "value": "{{(index .app.spec.sources 1).repoURL}}",
                                "inline": false
                              }
                              {{range $index, $c := .app.status.conditions}}
                              {{if $index}},{{end}}
                              {
                                "name": "{{$c.type}}",
                                "value": "{{$c.message}}",
                                "inline": true
                              }
                              {{end}}
                            ]
                          }
                        ]
                      }
    - repoURL: 'https://github.com/bobmaertz/home-ops.git'
      targetRevision: HEAD
      path: kubernetes/orion/manifests/infra/argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
