---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://github.com/bobmaertz/home-ops.git'
      targetRevision: HEAD
      path: kubernetes/orion/manifests/infra/cert-manager/
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.19.1
      helm:
        parameters:
          - name: installCRDs
            value: "true"
          - name: enableGatewayAPI
            value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
