---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://helm.cilium.io/
      targetRevision: 1.17.1
      chart: cilium
      helm:
        parameters:
        - name:  ipam.mode
          value: "kubernetes"
        - name:  kubeProxyReplacement
          value: "true"
        - name: securityContext.capabilities.ciliumAgent
          value: "{NET_BIND_SERVICE,CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
        - name: securityContext.capabilities.cleanCiliumState
          value: "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
        - name: cgroup.autoMount.enabled
          value: "false"
        - name: cgroup.hostRoot
          value: "/sys/fs/cgroup"
        - name: k8sServiceHost
          value: "localhost"
        - name: k8sServicePort
          value: "7445"
        - name: gatewayAPI.enabled
          value: "true"
        - name: envoy.securityContext.capabilities.keepCapNetBindService
          value: "true"
        - name: "hubble.relay.enabled"
          value: "true"
        - name: "hubble.ui.enabled"
          value: "true"
        - name: "l2announcements.enabled"
          value: "true"
          ## TODO: QOS / Burst
    # - repoURL: 'https://github.com/bobmaertz/home-ops.git'
    #   targetRevision: HEAD
    #   path: kubernetes/orion/manifests/infra/istio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true