---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  destination:
    namespace: registry 
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: 'https://github.com/bobmaertz/registry.git'
    targetRevision: HEAD
    path: .
  - repoURL: 'https://github.com/bobmaertz/home-ops.git'
    targetRevision: HEAD
    path: kubernetes/orion/manifests/infra/registry/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
