---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-github-pat
  namespace: actions-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: arc-github-pat
  data:
    - secretKey: github_token
      remoteRef:
        key: "arc_github_pat"
        property: credential
