---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-secret
  namespace: prometheus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: alertmanager-discord-secret
  data:
    - secretKey: discord-webhook-url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "Discord - Orion Deployment Webhook"
        metadataPolicy: None
        property: credential
