apiVersion: v1
kind: Namespace
metadata:
  name: fluent-bit
  annotations:
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/default-seccomp-profile: "runtime/default"