---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
  namespace: argocd
spec:
  destination:
    namespace: security
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: 1password
    repoURL: https://1password.github.io/connect-helm-charts
    helm:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
