apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: cloudflare-api-token-secret
    template:
      data:
        api-token: "{{ .credential }}"
  dataFrom:
    - extract:
        key: cloudflare_api_key
        property: credential