apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-pvc-assets
  namespace: homer
spec:
  storageClassName: ""
  volumeName: homer-pv-nfs-assets
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
