apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-pvc-config
  namespace: heimdall
spec:
  storageClassName: ""
  volumeName: heimdall-pv-nfs-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
