apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        orion: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            key: token
            name: op-connect-token
            namespace: external-secrets